- hosts: ubuntu-skunkwerks
  gather_facts: yes
  become: true
  become_user: root

  tasks:
    - name: Update apt and install required system packages
      apt:
        pkg:
          - nano
          - fish
        state: latest
        update_cache: true
    - name: enable fish
      ansible.builtin.shell: sudo usermod -s /usr/bin/fish $USER
      become: true   # Ensure that the highest permissions are used on the remote host

